<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CPC-ShaikIrF-B1" failures="1" tests="1" name="Joinnow_CST_Scenarios(failed)(failed)(failed)(failed)" time="84.032" errors="0" timestamp="2023-05-17T22:21:17 IST">
  <testcase classname="com.test.user.Joinnow_CST_Scenarios" name="RUNALL" time="81.433">
    <failure type="java.lang.Exception" message="java.lang.AssertionError: Additional Member 3 mobile not validated expected [9848033119] but found [9848022551]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at com.pages.Joinnow_CST.user_AMdetails_inreviewpage_for4persons(Joinnow_CST.java:16758)
	at com.pages.Joinnow_CST.Validate_MI_inRP_for4persons(Joinnow_CST.java:16883)
	at com.test.user.Joinnow_CST_Scenarios.RUNALL(Joinnow_CST_Scenarios.java:868)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: Additional Member 3 mobile not validated expected [9848033119] but found [9848022551]
at com.pages.Joinnow_CST.user_AMdetails_inreviewpage_for4persons(Joinnow_CST.java:16758)
at com.pages.Joinnow_CST.Validate_MI_inRP_for4persons(Joinnow_CST.java:16883)
at com.test.user.Joinnow_CST_Scenarios.RUNALL(Joinnow_CST_Scenarios.java:868)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

at com.test.user.Joinnow_CST_Scenarios.RUNALL(Joinnow_CST_Scenarios.java:1058)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 55 stack frames]]>
    </failure>
  </testcase> <!-- RUNALL -->
</testsuite> <!-- Joinnow_CST_Scenarios(failed)(failed)(failed)(failed) -->
